[profile.default]
src = "src"
out = "out"
libs = ["lib"]

 remappings = [
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/',
  'solmate/=lib/solmate/src/',
  '@openzeppelin/=lib/openzeppelin-contracts/'
]

fs_permissions = [
    { access = "read", path = "./broadcast"},
    { access = "read", path = "./reports"},
]

[fuzz]
runs = 256